/**
 * ═══════════════════════════════════════════════════════════════
 * 💊 Medications Seed Data - أكثر 30 دواء استخداماً في العراق
 * ═══════════════════════════════════════════════════════════════
 */

export interface MedicationSeed {
  name_ar: string;
  name_en?: string;
  generic_name?: string;
  manufacturer?: string;
  country_of_origin?: string;
  category: 'analgesic' | 'antibiotic' | 'antihistamine' | 'antacid' | 'vitamin' | 'chronic' | 'cold_flu' | 'other';
  form?: string;
  strength?: string;
  unit_type?: string;
  package_size?: string;
  requires_prescription: boolean;
  description?: string;
  is_active?: boolean;
}

export const MEDICATIONS_SEED: MedicationSeed[] = [
  // ─── مسكنات (Analgesics) ───
  {
    name_ar: 'باراسيتامول',
    name_en: 'Paracetamol',
    generic_name: 'Acetaminophen',
    manufacturer: 'SDI',
    country_of_origin: 'العراق',
    category: 'analgesic',
    form: 'حبوب',
    strength: '500mg',
    unit_type: 'tablet',
    package_size: '20 حبة',
    requires_prescription: false,
    description: 'مسكّن وخافض للحرارة',
  },
  {
    name_ar: 'بانادول إكسترا',
    name_en: 'Panadol Extra',
    manufacturer: 'GSK',
    country_of_origin: 'بريطانيا',
    category: 'analgesic',
    form: 'حبوب',
    strength: '500mg + 65mg كافيين',
    package_size: '24 حبة',
    requires_prescription: false,
  },
  {
    name_ar: 'إيبوبروفين',
    name_en: 'Ibuprofen',
    generic_name: 'Ibuprofen',
    category: 'analgesic',
    form: 'حبوب',
    strength: '400mg',
    package_size: '20 حبة',
    requires_prescription: false,
    description: 'مسكّن ومضاد للالتهابات',
  },
  {
    name_ar: 'فولتارين 50',
    name_en: 'Voltaren',
    generic_name: 'Diclofenac',
    manufacturer: 'Novartis',
    category: 'analgesic',
    form: 'حبوب',
    strength: '50mg',
    package_size: '20 حبة',
    requires_prescription: true,
    description: 'لآلام المفاصل والعضلات',
  },
  {
    name_ar: 'بروفين',
    name_en: 'Brufen',
    generic_name: 'Ibuprofen',
    category: 'analgesic',
    form: 'شراب',
    strength: '100mg/5ml',
    package_size: '100ml',
    requires_prescription: false,
    description: 'للأطفال - خافض للحرارة',
  },

  // ─── مضادات حيوية (Antibiotics) ───
  {
    name_ar: 'أموكسيسيلين',
    name_en: 'Amoxicillin',
    category: 'antibiotic',
    form: 'كبسولات',
    strength: '500mg',
    package_size: '21 كبسولة',
    requires_prescription: true,
  },
  {
    name_ar: 'أوغمنتين 1g',
    name_en: 'Augmentin',
    generic_name: 'Amoxicillin + Clavulanic',
    manufacturer: 'GSK',
    category: 'antibiotic',
    form: 'حبوب',
    strength: '1g',
    package_size: '14 حبة',
    requires_prescription: true,
  },
  {
    name_ar: 'زيثروماكس',
    name_en: 'Zithromax',
    generic_name: 'Azithromycin',
    manufacturer: 'Pfizer',
    category: 'antibiotic',
    form: 'حبوب',
    strength: '500mg',
    package_size: '3 حبوب',
    requires_prescription: true,
  },
  {
    name_ar: 'سيبروكسين',
    name_en: 'Ciproxin',
    generic_name: 'Ciprofloxacin',
    manufacturer: 'Bayer',
    category: 'antibiotic',
    form: 'حبوب',
    strength: '500mg',
    package_size: '10 حبوب',
    requires_prescription: true,
  },

  // ─── مضادات الحساسية (Antihistamines) ───
  {
    name_ar: 'لوراتادين',
    name_en: 'Loratadine',
    category: 'antihistamine',
    form: 'حبوب',
    strength: '10mg',
    package_size: '10 حبوب',
    requires_prescription: false,
    description: 'لحساسية الأنف والعين',
  },
  {
    name_ar: 'كلاريتين',
    name_en: 'Claritine',
    generic_name: 'Loratadine',
    manufacturer: 'Bayer',
    category: 'antihistamine',
    form: 'حبوب',
    strength: '10mg',
    package_size: '10 حبوب',
    requires_prescription: false,
  },
  {
    name_ar: 'تليفاست',
    name_en: 'Telfast',
    generic_name: 'Fexofenadine',
    category: 'antihistamine',
    form: 'حبوب',
    strength: '120mg',
    package_size: '10 حبوب',
    requires_prescription: false,
  },

  // ─── أدوية المعدة (Antacids) ───
  {
    name_ar: 'أوميبرازول',
    name_en: 'Omeprazole',
    category: 'antacid',
    form: 'كبسولات',
    strength: '20mg',
    package_size: '14 كبسولة',
    requires_prescription: false,
    description: 'لحموضة المعدة وقرحة',
  },
  {
    name_ar: 'نكسيوم',
    name_en: 'Nexium',
    generic_name: 'Esomeprazole',
    manufacturer: 'AstraZeneca',
    category: 'antacid',
    form: 'حبوب',
    strength: '40mg',
    package_size: '14 حبة',
    requires_prescription: true,
  },
  {
    name_ar: 'موتيليوم',
    name_en: 'Motilium',
    generic_name: 'Domperidone',
    category: 'antacid',
    form: 'حبوب',
    strength: '10mg',
    package_size: '30 حبة',
    requires_prescription: false,
    description: 'للغثيان واضطرابات المعدة',
  },
  {
    name_ar: 'مالوكس',
    name_en: 'Maalox',
    category: 'antacid',
    form: 'شراب',
    package_size: '180ml',
    requires_prescription: false,
  },

  // ─── أدوية الأمراض المزمنة ───
  {
    name_ar: 'ميتفورمين',
    name_en: 'Metformin',
    category: 'chronic',
    form: 'حبوب',
    strength: '500mg',
    package_size: '60 حبة',
    requires_prescription: true,
    description: 'لمرضى السكري النوع الثاني',
  },
  {
    name_ar: 'كونكور',
    name_en: 'Concor',
    generic_name: 'Bisoprolol',
    manufacturer: 'Merck',
    category: 'chronic',
    form: 'حبوب',
    strength: '5mg',
    package_size: '30 حبة',
    requires_prescription: true,
    description: 'لضغط الدم',
  },
  {
    name_ar: 'أتورفاستاتين',
    name_en: 'Atorvastatin',
    category: 'chronic',
    form: 'حبوب',
    strength: '20mg',
    package_size: '30 حبة',
    requires_prescription: true,
    description: 'لخفض الكوليسترول',
  },
  {
    name_ar: 'كابوتن',
    name_en: 'Capoten',
    generic_name: 'Captopril',
    category: 'chronic',
    form: 'حبوب',
    strength: '25mg',
    package_size: '30 حبة',
    requires_prescription: true,
    description: 'لارتفاع ضغط الدم',
  },
  {
    name_ar: 'يوثيروكس',
    name_en: 'Euthyrox',
    generic_name: 'Levothyroxine',
    manufacturer: 'Merck',
    category: 'chronic',
    form: 'حبوب',
    strength: '50mcg',
    package_size: '50 حبة',
    requires_prescription: true,
    description: 'لقصور الغدة الدرقية',
  },

  // ─── الفيتامينات ───
  {
    name_ar: 'فيتامين د3',
    name_en: 'Vitamin D3',
    category: 'vitamin',
    form: 'حبوب',
    strength: '5000 IU',
    package_size: '30 حبة',
    requires_prescription: false,
  },
  {
    name_ar: 'سنتروم',
    name_en: 'Centrum',
    manufacturer: 'Pfizer',
    category: 'vitamin',
    form: 'حبوب',
    package_size: '30 حبة',
    requires_prescription: false,
    description: 'فيتامينات ومعادن متكاملة',
  },
  {
    name_ar: 'فيروز',
    name_en: 'Ferrose',
    generic_name: 'Iron',
    category: 'vitamin',
    form: 'حبوب',
    strength: '50mg',
    package_size: '30 حبة',
    requires_prescription: false,
    description: 'لعلاج فقر الدم',
  },
  {
    name_ar: 'فولات',
    name_en: 'Folate',
    generic_name: 'Folic Acid',
    category: 'vitamin',
    form: 'حبوب',
    strength: '5mg',
    package_size: '30 حبة',
    requires_prescription: false,
    description: 'مهم للحوامل',
  },

  // ─── أدوية البرد ───
  {
    name_ar: 'فلو إن كولد',
    name_en: 'Flu & Cold',
    category: 'cold_flu',
    form: 'حبوب',
    package_size: '12 حبة',
    requires_prescription: false,
  },
  {
    name_ar: 'سترسلز',
    name_en: 'Strepsils',
    category: 'cold_flu',
    form: 'مستحلبات',
    package_size: '24 مستحلب',
    requires_prescription: false,
    description: 'لالتهاب الحلق',
  },
  {
    name_ar: 'فنتولين بخاخ',
    name_en: 'Ventolin Inhaler',
    generic_name: 'Salbutamol',
    manufacturer: 'GSK',
    category: 'other',
    form: 'بخاخ',
    strength: '100mcg',
    requires_prescription: true,
    description: 'لأزمة الربو',
  },
  {
    name_ar: 'بروسبان',
    name_en: 'Prospan',
    category: 'cold_flu',
    form: 'شراب',
    package_size: '100ml',
    requires_prescription: false,
    description: 'مذيب للسعال - طبيعي',
  },
  {
    name_ar: 'فيكس فيبوراب',
    name_en: 'Vicks VapoRub',
    category: 'cold_flu',
    form: 'مرهم',
    package_size: '50g',
    requires_prescription: false,
    description: 'مرهم للبرد والاحتقان',
  },
];
